
default: &default
  username: postgres
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: projeto_development


test:
  <<: *default
  database: projeto_test

production:
  <<: *default
  database: projeto_production
